name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@3.02
        with:
          name: painfulteam/fear-engine
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
